"""decouple model name from api key

Revision ID: 04510c628d51
Revises: 86dacd76e074
Create Date: 2024-07-19 18:53:14.325007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '04510c628d51'
down_revision = '86dacd76e074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.drop_column('model_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))

    # ### end Alembic commands ###
